### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by p1q** [p1q/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by promoacc** [comment]
### DONALD TRUMP
* https://www.fb.com/DonaldTrump
* realDonaldTrump@whitehouse.gov
* https://twitter.com/realDonaldTrump
* https://www.instagram.com/realDonaldTrump/

**Comment by p1q** [comment]
Well done!
